"""schema initial villes clusters trajets

Revision ID: eb29a9fe9301
Revises:
Create Date: 2026-06-25 14:23:26.350532

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eb29a9fe9301"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("row_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("city_name", sa.String(), nullable=False),
        sa.Column("lat_insee", sa.Float(), nullable=True),
        sa.Column("lon_insee", sa.Float(), nullable=True),
        sa.Column("cluster", sa.Integer(), nullable=False),
        sa.Column("cluster_nom", sa.String(), nullable=True),
        sa.Column("niveau_fragilite", sa.String(), nullable=True),
        sa.Column("has_gare", sa.Boolean(), nullable=True),
        sa.Column("accessibilite_ord", sa.Integer(), nullable=True),
        sa.Column("dist_gare_min_m", sa.Float(), nullable=True),
        sa.Column("nb_trajets_total", sa.Float(), nullable=True),
        sa.Column("nb_lignes_total", sa.Float(), nullable=True),
        sa.Column("amplitude_moy_h", sa.Float(), nullable=True),
        sa.Column("revenu_median_uc", sa.Float(), nullable=True),
        sa.Column("voitures_par_menage", sa.Float(), nullable=True),
        sa.Column("taux_sans_voiture", sa.Float(), nullable=True),
        sa.Column("part_65plus", sa.Float(), nullable=True),
        sa.Column("distance_dom_trav_med_km", sa.Float(), nullable=True),
        sa.Column("population", sa.Float(), nullable=True),
        sa.Column("densite_pop_km2", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("row_id"),
    )
    op.create_index(op.f("ix_clusters_city_name"), "clusters", ["city_name"], unique=False)
    op.create_index(op.f("ix_clusters_cluster"), "clusters", ["cluster"], unique=False)
    op.create_index(
        op.f("ix_clusters_niveau_fragilite"), "clusters", ["niveau_fragilite"], unique=False
    )
    op.create_table(
        "trajets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(), nullable=True),
        sa.Column("trip_id", sa.String(), nullable=True),
        sa.Column("mode", sa.String(), nullable=True),
        sa.Column("destination", sa.String(), nullable=True),
        sa.Column("trip_short_name", sa.String(), nullable=True),
        sa.Column("agency_name", sa.String(), nullable=True),
        sa.Column("agency_timezone", sa.String(), nullable=True),
        sa.Column("service_id", sa.String(), nullable=True),
        sa.Column("route_id", sa.String(), nullable=True),
        sa.Column("route_type", sa.Integer(), nullable=True),
        sa.Column("route_short_name", sa.String(), nullable=True),
        sa.Column("route_long_name", sa.String(), nullable=True),
        sa.Column("departure_station", sa.String(), nullable=True),
        sa.Column("departure_city", sa.String(), nullable=True),
        sa.Column("departure_country", sa.String(length=2), nullable=True),
        sa.Column("departure_time", sa.String(), nullable=True),
        sa.Column("departure_parent_station", sa.String(), nullable=True),
        sa.Column("arrival_station", sa.String(), nullable=True),
        sa.Column("arrival_city", sa.String(), nullable=True),
        sa.Column("arrival_country", sa.String(length=2), nullable=True),
        sa.Column("arrival_time", sa.String(), nullable=True),
        sa.Column("arrival_parent_station", sa.String(), nullable=True),
        sa.Column("service_start_date", sa.Date(), nullable=True),
        sa.Column("service_end_date", sa.Date(), nullable=True),
        sa.Column("days_of_week", sa.String(length=7), nullable=True),
        sa.Column("is_night_train", sa.Boolean(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column("co2_per_pkm", sa.Float(), nullable=True),
        sa.Column("emissions_co2", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trajets_agency_name"), "trajets", ["agency_name"], unique=False)
    op.create_index(op.f("ix_trajets_arrival_city"), "trajets", ["arrival_city"], unique=False)
    op.create_index(
        op.f("ix_trajets_arrival_country"), "trajets", ["arrival_country"], unique=False
    )
    op.create_index(op.f("ix_trajets_departure_city"), "trajets", ["departure_city"], unique=False)
    op.create_index(
        op.f("ix_trajets_departure_country"), "trajets", ["departure_country"], unique=False
    )
    op.create_index(op.f("ix_trajets_is_night_train"), "trajets", ["is_night_train"], unique=False)
    op.create_index(op.f("ix_trajets_mode"), "trajets", ["mode"], unique=False)
    op.create_index(
        op.f("ix_trajets_service_end_date"), "trajets", ["service_end_date"], unique=False
    )
    op.create_index(
        op.f("ix_trajets_service_start_date"), "trajets", ["service_start_date"], unique=False
    )
    op.create_index(op.f("ix_trajets_trip_id"), "trajets", ["trip_id"], unique=False)
    op.create_table(
        "villes",
        sa.Column("citycode", sa.String(length=10), nullable=False),
        sa.Column("city_name", sa.String(), nullable=False),
        sa.Column("nom_insee", sa.String(), nullable=True),
        sa.Column("lat_insee", sa.Float(), nullable=True),
        sa.Column("lon_insee", sa.Float(), nullable=True),
        sa.Column("code_dept", sa.String(length=3), nullable=True),
        sa.Column("code_region", sa.String(length=3), nullable=True),
        sa.Column("population_insee", sa.Float(), nullable=True),
        sa.Column("surface_km2", sa.Float(), nullable=True),
        sa.Column("densite_pop_km2", sa.Float(), nullable=True),
        sa.Column("revenu_median_uc", sa.Float(), nullable=True),
        sa.Column("taux_sans_voiture", sa.Float(), nullable=True),
        sa.Column("voitures_par_menage", sa.Float(), nullable=True),
        sa.Column("part_65plus", sa.Float(), nullable=True),
        sa.Column("distance_dom_trav_med_km", sa.Float(), nullable=True),
        sa.Column("nb_gares", sa.Integer(), nullable=True),
        sa.Column("nb_trajets_total", sa.Integer(), nullable=True),
        sa.Column("nb_trajets_moy_arret", sa.Float(), nullable=True),
        sa.Column("nb_trajets_max_arret", sa.Integer(), nullable=True),
        sa.Column("nb_lignes_total", sa.Integer(), nullable=True),
        sa.Column("premier_depart_matin", sa.String(length=8), nullable=True),
        sa.Column("dernier_depart_ville", sa.String(length=8), nullable=True),
        sa.Column("amplitude_moy_h", sa.Float(), nullable=True),
        sa.Column("amplitude_max_h", sa.Float(), nullable=True),
        sa.Column("amplitude_min_h", sa.Float(), nullable=True),
        sa.Column("service_weekend", sa.Boolean(), nullable=True),
        sa.Column("service_7j_sur_7", sa.Boolean(), nullable=True),
        sa.Column("dist_gare_min_m", sa.Float(), nullable=True),
        sa.Column("has_gare", sa.Boolean(), nullable=True),
        sa.Column("accessibilite_ord", sa.Integer(), nullable=True),
        sa.Column("dernier_depart_apres_minuit", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("citycode"),
    )
    op.create_index(op.f("ix_villes_city_name"), "villes", ["city_name"], unique=False)
    op.create_index(op.f("ix_villes_code_dept"), "villes", ["code_dept"], unique=False)
    op.create_index(op.f("ix_villes_code_region"), "villes", ["code_region"], unique=False)
    op.create_index(op.f("ix_villes_has_gare"), "villes", ["has_gare"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_villes_has_gare"), table_name="villes")
    op.drop_index(op.f("ix_villes_code_region"), table_name="villes")
    op.drop_index(op.f("ix_villes_code_dept"), table_name="villes")
    op.drop_index(op.f("ix_villes_city_name"), table_name="villes")
    op.drop_table("villes")
    op.drop_index(op.f("ix_trajets_trip_id"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_service_start_date"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_service_end_date"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_mode"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_is_night_train"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_departure_country"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_departure_city"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_arrival_country"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_arrival_city"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_agency_name"), table_name="trajets")
    op.drop_table("trajets")
    op.drop_index(op.f("ix_clusters_niveau_fragilite"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_cluster"), table_name="clusters")
    op.drop_index(op.f("ix_clusters_city_name"), table_name="clusters")
    op.drop_table("clusters")
    # ### end Alembic commands ###
