"""resolution jointures citycode clusters et trajets

Revision ID: f71902521a81
Revises: eb29a9fe9301
Create Date: 2026-06-25 14:58:22.605259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f71902521a81"
down_revision: str | Sequence[str] | None = "eb29a9fe9301"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clusters", sa.Column("citycode", sa.String(length=10), nullable=True))
    op.create_index(op.f("ix_clusters_citycode"), "clusters", ["citycode"], unique=False)
    op.create_foreign_key(None, "clusters", "villes", ["citycode"], ["citycode"])
    op.add_column("trajets", sa.Column("departure_citycode", sa.String(length=10), nullable=True))
    op.add_column("trajets", sa.Column("arrival_citycode", sa.String(length=10), nullable=True))
    op.create_index(
        op.f("ix_trajets_arrival_citycode"), "trajets", ["arrival_citycode"], unique=False
    )
    op.create_index(
        op.f("ix_trajets_departure_citycode"), "trajets", ["departure_citycode"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trajets_departure_citycode"), table_name="trajets")
    op.drop_index(op.f("ix_trajets_arrival_citycode"), table_name="trajets")
    op.drop_column("trajets", "arrival_citycode")
    op.drop_column("trajets", "departure_citycode")
    op.drop_constraint(None, "clusters", type_="foreignkey")
    op.drop_index(op.f("ix_clusters_citycode"), table_name="clusters")
    op.drop_column("clusters", "citycode")
    # ### end Alembic commands ###
