services:

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ObRailEurope
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/ObRailEurope
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data: