services:

  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ObRailEurope
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/ObRailEurope
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  postgres_data:

# Utilisation :
#   Toutes les phases         : docker compose run --rm etl
#   Extraction seulement      : docker compose run --rm etl --phases extraction
#   Transformation seulement  : docker compose run --rm etl --phases transform
#   Chargement seulement      : docker compose run --rm etl --phases load
#   Extraction + Transformation : docker compose run --rm etl --phases extraction transform
#   Extraction + Chargement   : docker compose run --rm etl --phases extraction load
#   Rebuild l'image           : docker compose build
#   Arrêter tout              : docker compose down
#   Arrêter et nettoyer       : docker compose down -v